export namespace status {
  let CONTINUE: 100
  let SWITCHING_PROTOCOLS: 101
  let PROCESSING: 102
  let EARLY_HINTS: 103
  let OK: 200
  let CREATED: 201
  let ACCEPTED: 202
  let NON_AUTHORITATIVE_INFORMATION: 203
  let NO_CONTENT: 204
  let RESET_CONTENT: 205
  let PARTIAL_CONTENT: 206
  let MULTI_STATUS: 207
  let ALREADY_REPORTED: 208
  let IM_USED: 226
  let MULTIPLE_CHOICES: 300
  let MOVED_PERMANENTLY: 301
  let FOUND: 302
  let SEE_OTHER: 303
  let NOT_MODIFIED: 304
  let USE_PROXY: 305
  let TEMPORARY_REDIRECT: 307
  let PERMANENT_REDIRECT: 308
  let BAD_REQUEST: 400
  let UNAUTHORIZED: 401
  let PAYMENT_REQUIRED: 402
  let FORBIDDEN: 403
  let NOT_FOUND: 404
  let METHOD_NOT_ALLOWED: 405
  let NOT_ACCEPTABLE: 406
  let PROXY_AUTHENTICATION_REQUIRED: 407
  let REQUEST_TIMEOUT: 408
  let CONFLICT: 409
  let GONE: 410
  let LENGTH_REQUIRED: 411
  let PRECONDITION_FAILED: 412
  let PAYLOAD_TOO_LARGE: 413
  let URI_TOO_LONG: 414
  let UNSUPPORTED_MEDIA_TYPE: 415
  let RANGE_NOT_SATISFIABLE: 416
  let EXPECTATION_FAILED: 417
  let IM_A_TEAPOT: 418
  let MISDIRECTED_REQUEST: 421
  let UNPROCESSABLE_ENTITY: 422
  let LOCKED: 423
  let FAILED_DEPENDENCY: 424
  let TOO_EARLY: 425
  let UPGRADE_REQUIRED: 426
  let PRECONDITION_REQUIRED: 428
  let TOO_MANY_REQUESTS: 429
  let REQUEST_HEADER_FIELDS_TOO_LARGE: 431
  let UNAVAILABLE_FOR_LEGAL_REASONS: 451
  let CLIENT_CLOSED_REQUEST: 499
  let INTERNAL_SERVER_ERROR: 500
  let NOT_IMPLEMENTED: 501
  let BAD_GATEWAY: 502
  let SERVICE_UNAVAILABLE: 503
  let GATEWAY_TIMEOUT: 504
  let HTTP_VERSION_NOT_SUPPORTED: 505
  let VARIANT_ALSO_NEGOTIATES: 506
  let INSUFFICIENT_STORAGE: 507
  let LOOP_DETECTED: 508
  let NOT_EXTENDED: 510
  let NETWORK_AUTHENTICATION_REQUIRED: 511
}
export namespace methods {
  let GET: 'GET'
  let POST: 'POST'
  let PUT: 'PUT'
  let DELETE: 'DELETE'
  let PATCH: 'PATCH'
  let HEAD: 'HEAD'
  let OPTIONS: 'OPTIONS'
  let CONNECT: 'CONNECT'
  let TRACE: 'TRACE'
}
export namespace headers {
  let ACCEPT: 'Accept'
  let ACCEPT_CHARSET: 'Accept-Charset'
  let ACCEPT_DATETIME: 'Accept-Datetime'
  let ACCEPT_ENCODING: 'Accept-Encoding'
  let ACCEPT_LANGUAGE: 'Accept-Language'
  let AUTHORIZATION: 'Authorization'
  let CACHE_CONTROL: 'Cache-Control'
  let CONNECTION: 'Connection'
  let CONTENT_LENGTH: 'Content-Length'
  let CONTENT_MD5: 'Content-MD5'
  let CONTENT_TYPE: 'Content-Type'
  let COOKIE: 'Cookie'
  let DATE: 'Date'
  let EXPECT: 'Expect'
  let FORWARDED: 'Forwarded'
  let FROM: 'From'
  let HOST: 'Host'
  let IF_MATCH: 'If-Match'
  let IF_MODIFIED_SINCE: 'If-Modified-Since'
  let IF_NONE_MATCH: 'If-None-Match'
  let IF_RANGE: 'If-Range'
  let IF_UNMODIFIED_SINCE: 'If-Unmodified-Since'
  let MAX_FORWARDS: 'Max-Forwards'
  let ORIGIN: 'Origin'
  let PRAGMA: 'Pragma'
  let PROXY_AUTHORIZATION: 'Proxy-Authorization'
  let RANGE: 'Range'
  let REFERER: 'Referer'
  let TE: 'TE'
  let TRANSFER_ENCODING: 'Transfer-Encoding'
  let UPGRADE: 'Upgrade'
  let USER_AGENT: 'User-Agent'
  let VIA: 'Via'
  let WARNING: 'Warning'
  let ACCEPT_PATCH: 'Accept-Patch'
  let ACCEPT_RANGES: 'Accept-Ranges'
  let ACCESS_CONTROL_ALLOW_CREDENTIALS: 'Access-Control-Allow-Credentials'
  let ACCESS_CONTROL_ALLOW_HEADERS: 'Access-Control-Allow-Headers'
  let ACCESS_CONTROL_ALLOW_METHODS: 'Access-Control-Allow-Methods'
  let ACCESS_CONTROL_ALLOW_ORIGIN: 'Access-Control-Allow-Origin'
  let ACCESS_CONTROL_EXPOSE_HEADERS: 'Access-Control-Expose-Headers'
  let ACCESS_CONTROL_MAX_AGE: 'Access-Control-Max-Age'
  let AGE: 'Age'
  let ALLOW: 'Allow'
  let ALT_SVC: 'Alt-Svc'
  let CONTENT_DISPOSITION: 'Content-Disposition'
  let CONTENT_ENCODING: 'Content-Encoding'
  let CONTENT_LANGUAGE: 'Content-Language'
  let CONTENT_LOCATION: 'Content-Location'
  let CONTENT_RANGE: 'Content-Range'
  let DELTA_BASE: 'Delta-Base'
  let ETAG: 'ETag'
  let EXPIRES: 'Expires'
  let IM: 'IM'
  let LAST_MODIFIED: 'Last-Modified'
  let LINK: 'Link'
  let LOCATION: 'Location'
  let P3P: 'P3P'
  let PROXY_AUTHENTICATE: 'Proxy-Authenticate'
  let PUBLIC_KEY_PINS: 'Public-Key-Pins'
  let RETRY_AFTER: 'Retry-After'
  let SERVER: 'Server'
  let SET_COOKIE: 'Set-Cookie'
  let STRICT_TRANSPORT_SECURITY: 'Strict-Transport-Security'
  let TRAILER: 'Trailer'
  let VARY: 'Vary'
  let WWW_AUTHENTICATE: 'WWW-Authenticate'
  let X_FRAME_OPTIONS: 'X-Frame-Options'
  let DNT: 'DNT'
  let FRONT_END_HTTPS: 'Front-End-Https'
  let PROXY_CONNECTION: 'Proxy-Connection'
  let SAVE_DATA: 'Save-Data'
  let X_ATT_DEVICEID: 'X-ATT-DeviceId'
  let X_CORRELATION_ID: 'X-Correlation-ID'
  let X_CSRF_TOKEN: 'X-CSRF-Token'
  let X_FORWARDED_FOR: 'X-Forwarded-For'
  let X_FORWARDED_HOST: 'X-Forwarded-Host'
  let X_FORWARDED_PROTO: 'X-Forwarded-Proto'
  let X_HTTP_METHOD_OVERRIDE: 'X-HTTP-Method-Override'
  let X_REQUESTED_WITH: 'X-Requested-With'
  let X_REQUEST_ID: 'X-Request-ID'
  let X_UIDH: 'X-UIDH'
  let X_WAP_PROFILE: 'X-Wap-Profile'
  let CONTENT_SECURITY_POLICY: 'Content-Security-Policy'
  let CONTENT_SECURITY_POLICY_REPORT_ONLY: 'Content-Security-Policy-Report-Only'
  let FEATURE_POLICY: 'Feature-Policy'
  let PERMISSIONS_POLICY: 'Permissions-Policy'
  let REFERRER_POLICY: 'Referrer-Policy'
  let X_CONTENT_TYPE_OPTIONS: 'X-Content-Type-Options'
  let X_XSS_PROTECTION: 'X-XSS-Protection'
  let CROSS_ORIGIN_EMBEDDER_POLICY: 'Cross-Origin-Embedder-Policy'
  let CROSS_ORIGIN_OPENER_POLICY: 'Cross-Origin-Opener-Policy'
  let CROSS_ORIGIN_RESOURCE_POLICY: 'Cross-Origin-Resource-Policy'
  let EXPECT_CT: 'Expect-CT'
  let ORIGIN_AGENT_CLUSTER: 'Origin-Agent-Cluster'
  let REPORT_TO: 'Report-To'
  let REPORTING_ENDPOINTS: 'Reporting-Endpoints'
  let ACCEPT_CH: 'Accept-CH'
  let ACCEPT_CH_LIFETIME: 'Accept-CH-Lifetime'
  let CRITICAL_CH: 'Critical-CH'
  let DEVICE_MEMORY: 'Device-Memory'
  let DOWNLINK: 'Downlink'
  let DPR: 'DPR'
  let ECT: 'ECT'
  let RTT: 'RTT'
  let VIEWPORT_WIDTH: 'Viewport-Width'
  let WIDTH: 'Width'
  let EARLY_DATA: 'Early-Data'
  let PRIORITY: 'Priority'
  let TIMING_ALLOW_ORIGIN: 'Timing-Allow-Origin'
}
export namespace constants {
  export { status }
  export { methods }
  export { headers }
}
export default constants
