export namespace status {
  let CONTINUE: 100
  let SWITCHING_PROTOCOLS: 101
  let PROCESSING: 102
  let EARLY_HINTS: 103
  let OK: 200
  let CREATED: 201
  let ACCEPTED: 202
  let NON_AUTHORITATIVE_INFORMATION: 203
  let NO_CONTENT: 204
  let RESET_CONTENT: 205
  let PARTIAL_CONTENT: 206
  let MULTI_STATUS: 207
  let ALREADY_REPORTED: 208
  let IM_USED: 226
  let MULTIPLE_CHOICES: 300
  let MOVED_PERMANENTLY: 301
  let FOUND: 302
  let SEE_OTHER: 303
  let NOT_MODIFIED: 304
  let USE_PROXY: 305
  let TEMPORARY_REDIRECT: 307
  let PERMANENT_REDIRECT: 308
  let BAD_REQUEST: 400
  let UNAUTHORIZED: 401
  let PAYMENT_REQUIRED: 402
  let FORBIDDEN: 403
  let NOT_FOUND: 404
  let METHOD_NOT_ALLOWED: 405
  let NOT_ACCEPTABLE: 406
  let PROXY_AUTHENTICATION_REQUIRED: 407
  let REQUEST_TIMEOUT: 408
  let CONFLICT: 409
  let GONE: 410
  let LENGTH_REQUIRED: 411
  let PRECONDITION_FAILED: 412
  let PAYLOAD_TOO_LARGE: 413
  let URI_TOO_LONG: 414
  let UNSUPPORTED_MEDIA_TYPE: 415
  let RANGE_NOT_SATISFIABLE: 416
  let EXPECTATION_FAILED: 417
  let IM_A_TEAPOT: 418
  let MISDIRECTED_REQUEST: 421
  let UNPROCESSABLE_ENTITY: 422
  let LOCKED: 423
  let FAILED_DEPENDENCY: 424
  let TOO_EARLY: 425
  let UPGRADE_REQUIRED: 426
  let PRECONDITION_REQUIRED: 428
  let TOO_MANY_REQUESTS: 429
  let REQUEST_HEADER_FIELDS_TOO_LARGE: 431
  let UNAVAILABLE_FOR_LEGAL_REASONS: 451
  let CLIENT_CLOSED_REQUEST: 499
  let INTERNAL_SERVER_ERROR: 500
  let NOT_IMPLEMENTED: 501
  let BAD_GATEWAY: 502
  let SERVICE_UNAVAILABLE: 503
  let GATEWAY_TIMEOUT: 504
  let HTTP_VERSION_NOT_SUPPORTED: 505
  let VARIANT_ALSO_NEGOTIATES: 506
  let INSUFFICIENT_STORAGE: 507
  let LOOP_DETECTED: 508
  let NOT_EXTENDED: 510
  let NETWORK_AUTHENTICATION_REQUIRED: 511
}
export namespace methods {
  let GET: 'GET'
  let POST: 'POST'
  let PUT: 'PUT'
  let DELETE: 'DELETE'
  let PATCH: 'PATCH'
  let HEAD: 'HEAD'
  let OPTIONS: 'OPTIONS'
  let CONNECT: 'CONNECT'
  let TRACE: 'TRACE'
}
export namespace headers {
  let ACCEPT: 'accept'
  let ACCEPT_CHARSET: 'accept-charset'
  let ACCEPT_ENCODING: 'accept-encoding'
  let ACCEPT_LANGUAGE: 'accept-language'
  let ACCEPT_DATETIME: 'accept-datetime'
  let AUTHORIZATION: 'authorization'
  let CACHE_CONTROL: 'cache-control'
  let CONNECTION: 'connection'
  let COOKIE: 'cookie'
  let CONTENT_LENGTH: 'content-length'
  let CONTENT_MD5: 'content-md5'
  let CONTENT_TYPE: 'content-type'
  let DATE: 'date'
  let EXPECT: 'expect'
  let FORWARDED: 'forwarded'
  let FROM: 'from'
  let HOST: 'host'
  let IF_MATCH: 'if-match'
  let IF_MODIFIED_SINCE: 'if-modified-since'
  let IF_NONE_MATCH: 'if-none-match'
  let IF_RANGE: 'if-range'
  let IF_UNMODIFIED_SINCE: 'if-unmodified-since'
  let MAX_FORWARDS: 'max-forwards'
  let ORIGIN: 'origin'
  let PRAGMA: 'pragma'
  let PROXY_AUTHORIZATION: 'proxy-authorization'
  let RANGE: 'range'
  let REFERER: 'referer'
  let TE: 'te'
  let TRANSFER_ENCODING: 'transfer-encoding'
  let USER_AGENT: 'user-agent'
  let UPGRADE: 'upgrade'
  let VIA: 'via'
  let WARNING: 'warning'
  let ACCESS_CONTROL_ALLOW_ORIGIN: 'access-control-allow-origin'
  let ACCESS_CONTROL_ALLOW_CREDENTIALS: 'access-control-allow-credentials'
  let ACCESS_CONTROL_EXPOSE_HEADERS: 'access-control-expose-headers'
  let ACCESS_CONTROL_MAX_AGE: 'access-control-max-age'
  let ACCESS_CONTROL_ALLOW_METHODS: 'access-control-allow-methods'
  let ACCESS_CONTROL_ALLOW_HEADERS: 'access-control-allow-headers'
  let ACCEPT_PATCH: 'accept-patch'
  let ACCEPT_RANGES: 'accept-ranges'
  let AGE: 'age'
  let ALLOW: 'allow'
  let ALT_SVC: 'alt-svc'
  let CONTENT_DISPOSITION: 'content-disposition'
  let CONTENT_ENCODING: 'content-encoding'
  let CONTENT_LANGUAGE: 'content-language'
  let CONTENT_LOCATION: 'content-location'
  let CONTENT_RANGE: 'content-range'
  let DELTA_BASE: 'delta-base'
  let ETAG: 'etag'
  let EXPIRES: 'expires'
  let IM: 'im'
  let LAST_MODIFIED: 'last-modified'
  let LINK: 'link'
  let LOCATION: 'location'
  let P3P: 'p3p'
  let PROXY_AUTHENTICATE: 'proxy-authenticate'
  let PUBLIC_KEY_PINS: 'public-key-pins'
  let RETRY_AFTER: 'retry-after'
  let SERVER: 'server'
  let SET_COOKIE: 'set-cookie'
  let STRICT_TRANSPORT_SECURITY: 'strict-transport-security'
  let TRAILER: 'trailer'
  let VARY: 'vary'
  let WWW_AUTHENTICATE: 'www-authenticate'
  let X_FRAME_OPTIONS: 'x-frame-options'
  let X_REQUESTED_WITH: 'x-requested-with'
  let DNT: 'dnt'
  let X_FORWARDED_FOR: 'x-forwarded-for'
  let X_FORWARDED_HOST: 'x-forwarded-host'
  let X_FORWARDED_PROTO: 'x-forwarded-proto'
  let FRONT_END_HTTPS: 'front-end-https'
  let X_HTTP_METHOD_OVERRIDE: 'x-http-method-override'
  let X_ATT_DEVICEID: 'x-att-deviceid'
  let X_WAP_PROFILE: 'x-wap-profile'
  let PROXY_CONNECTION: 'proxy-connection'
  let X_UIDH: 'x-uidh'
  let X_CSRF_TOKEN: 'x-csrf-token'
  let X_REQUEST_ID: 'x-request-id'
  let X_CORRELATION_ID: 'x-correlation-id'
  let SAVE_DATA: 'save-data'
  let CONTENT_SECURITY_POLICY: 'content-security-policy'
  let CONTENT_SECURITY_POLICY_REPORT_ONLY: 'content-security-policy-report-only'
  let X_CONTENT_TYPE_OPTIONS: 'x-content-type-options'
  let X_XSS_PROTECTION: 'x-xss-protection'
  let REFERRER_POLICY: 'referrer-policy'
  let FEATURE_POLICY: 'feature-policy'
  let PERMISSIONS_POLICY: 'permissions-policy'
}
export namespace constants {
  export { status }
  export { methods }
  export { headers }
}
export default constants
